from __future__ import annotations

import argparse
import ast
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "docs" / "file-health-report.md"

EXCLUDED_DIRS = {
    ".git",
    "__pycache__",
    ".venv",
    "venv",
    "node_modules",
    "dist",
    "deploy_staging",
}


@dataclass
class PythonFileHealth:
    path: Path
    size_bytes: int
    line_count: int
    function_count: int
    class_count: int
    import_count: int
    parse_error: str | None
    longest_functions: list[tuple[str, int, int]]


def _line_count(path: Path) -> int:
    try:
        with path.open("rb") as fh:
            return sum(1 for _ in fh)
    except OSError:
        return 0


def _iter_python_files(root: Path) -> list[Path]:
    files: list[Path] = []
    for path in root.rglob("*.py"):
        if any(part in EXCLUDED_DIRS for part in path.relative_to(root).parts):
            continue
        files.append(path)
    return sorted(files)


def analyze_python_file(path: Path) -> PythonFileHealth:
    size = path.stat().st_size if path.exists() else 0
    lines = _line_count(path)
    text = path.read_text(encoding="utf-8", errors="replace") if path.exists() else ""
    function_count = 0
    class_count = 0
    import_count = 0
    longest: list[tuple[str, int, int]] = []
    parse_error: str | None = None
    try:
        tree = ast.parse(text)
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                function_count += 1
                start = getattr(node, "lineno", 0) or 0
                end = getattr(node, "end_lineno", start) or start
                longest.append((node.name, start, max(0, end - start + 1)))
            elif isinstance(node, ast.ClassDef):
                class_count += 1
            elif isinstance(node, (ast.Import, ast.ImportFrom)):
                import_count += 1
    except SyntaxError as exc:
        parse_error = f"{exc.msg} at line {exc.lineno}"
    except Exception as exc:
        parse_error = f"{type(exc).__name__}: {exc}"
    longest.sort(key=lambda item: item[2], reverse=True)
    return PythonFileHealth(
        path=path,
        size_bytes=size,
        line_count=lines,
        function_count=function_count,
        class_count=class_count,
        import_count=import_count,
        parse_error=parse_error,
        longest_functions=longest[:12],
    )


def _warnings_for_app(health: PythonFileHealth) -> list[str]:
    warnings: list[str] = []
    if health.line_count > 500:
        warnings.append("warning: app.py exceeds 500 lines")
    if health.line_count > 1000:
        warnings.append("high warning: app.py exceeds 1000 lines")
    if health.size_bytes > 1_000_000:
        warnings.append("connector-risk warning: app.py exceeds 1 MB")
    if health.parse_error:
        warnings.append(f"parse warning: {health.parse_error}")
    return warnings


def _human_size(size: int) -> str:
    if size >= 1024 * 1024:
        return f"{size / (1024 * 1024):.2f} MB"
    if size >= 1024:
        return f"{size / 1024:.1f} KB"
    return f"{size} B"


def build_markdown(root: Path) -> str:
    app_path = root / "app.py"
    app = analyze_python_file(app_path)
    python_files = _iter_python_files(root)
    total_py_size = sum(path.stat().st_size for path in python_files)
    warnings = _warnings_for_app(app)
    longest_rows = "\n".join(
        f"| `{name}` | {line} | {length} |" for name, line, length in app.longest_functions
    ) or "| - | - | - |"
    file_rows = []
    for path in python_files[:80]:
        health = analyze_python_file(path)
        rel = path.relative_to(root).as_posix()
        file_rows.append(
            f"| `{rel}` | {_human_size(health.size_bytes)} | {health.line_count} | "
            f"{health.function_count} | {health.class_count} | {health.import_count} |"
        )
    return f"""# File Health Report

Generated by `scripts/file_health_report.py`.

## Summary
- Python files inspected: {len(python_files)}
- Total Python file size: {_human_size(total_py_size)}
- `app.py` size: {_human_size(app.size_bytes)}
- `app.py` lines: {app.line_count}
- `app.py` functions: {app.function_count}
- `app.py` classes: {app.class_count}
- `app.py` imports: {app.import_count}

## Warnings
{chr(10).join(f'- {item}' for item in warnings) if warnings else '- none'}

## Longest Functions In app.py
| Function | Start line | Lines |
| --- | ---: | ---: |
{longest_rows}

## Python File Inventory
| File | Size | Lines | Functions | Classes | Imports |
| --- | ---: | ---: | ---: | ---: | ---: |
{chr(10).join(file_rows)}
"""


def print_console_report(root: Path, markdown: str) -> None:
    app = analyze_python_file(root / "app.py")
    print("File health report")
    print(f"app.py size: {_human_size(app.size_bytes)}")
    print(f"app.py lines: {app.line_count}")
    print(f"app.py functions: {app.function_count}")
    print(f"app.py classes: {app.class_count}")
    print(f"app.py imports: {app.import_count}")
    for item in _warnings_for_app(app):
        print(item)
    print(f"markdown report bytes: {len(markdown.encode('utf-8'))}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Report app.py and project Python file health.")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="Markdown output path.")
    args = parser.parse_args(argv)
    root = ROOT
    output = Path(args.output)
    if not output.is_absolute():
        output = root / output
    output.parent.mkdir(parents=True, exist_ok=True)
    markdown = build_markdown(root)
    output.write_text(markdown, encoding="utf-8")
    print_console_report(root, markdown)
    print(f"wrote: {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
